version: "3.3"

services:
  db:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: KongLogging2022
    ports:
      - "27017:27017"

  request-logs:
    build: .
    container_name: request-logs
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "6600:3000"
    depends_on:
      - db
