version: "3.3"

services:
  db:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"

  api:
    build: .
    container_name: mimic-pools-api
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "6600:3000"
    depends_on:
      - db
